### ISSUE TITLE
ValueError: Extra-info digests should consist of forty hex digits

### ISSUE THREAD

**Issue by DrWhax** [NullHypothesis/exitmap#41] opened 2016-03-01 10:51 UTC
When trying to get exitmap to run and executing 'checktest' I get the following error:

```
./exitmap checktest
2016-03-01 11:47:06,584 [INFO]: Attempting to invoke Tor process in directory "/tmp/exitmap_tor_datadir-jurre".  This might take a while.
2016-03-01 11:47:06,585 [INFO]: No first hop given.  Using randomly determined first hops for circuits.
2016-03-01 11:47:06,853 [INFO]: Tor Bootstrapped 0%: Starting
2016-03-01 11:47:07,855 [INFO]: Tor Bootstrapped 5%: Connecting to directory server
2016-03-01 11:47:07,942 [INFO]: Tor Bootstrapped 10%: Finishing handshake with directory server
2016-03-01 11:47:08,261 [INFO]: Tor Bootstrapped 15%: Establishing an encrypted directory connection
2016-03-01 11:47:08,352 [INFO]: Tor Bootstrapped 20%: Asking for networkstatus consensus
2016-03-01 11:47:08,453 [INFO]: Tor Bootstrapped 25%: Loading networkstatus consensus
2016-03-01 11:47:16,315 [INFO]: Tor Bootstrapped 40%: Loading authority key certs
2016-03-01 11:47:17,106 [INFO]: Tor Bootstrapped 45%: Asking for relay descriptors
2016-03-01 11:47:17,712 [INFO]: Tor Bootstrapped 50%: Loading relay descriptors
2016-03-01 11:47:54,291 [INFO]: Tor Bootstrapped 55%: Loading relay descriptors
2016-03-01 11:47:55,107 [INFO]: Tor Bootstrapped 61%: Loading relay descriptors
2016-03-01 11:47:55,654 [INFO]: Tor Bootstrapped 69%: Loading relay descriptors
2016-03-01 11:47:55,911 [INFO]: Tor Bootstrapped 75%: Loading relay descriptors
2016-03-01 11:47:56,159 [INFO]: Tor Bootstrapped 80%: Connecting to the Tor network
2016-03-01 11:47:56,159 [INFO]: Successfully started Tor process (PID=4656).
2016-03-01 11:47:56,272 [INFO]: Running module 'checktest'.
Traceback (most recent call last):
  File "./exitmap", line 32, in <module>
    sys.exit(main())
  File "/home/jurre/dev/exitmap/src/exitmap.py", line 260, in main
    run_module(module_name, args, controller, socks_port, stats)
  File "/home/jurre/dev/exitmap/src/exitmap.py", line 341, in run_module
    exit_relays = select_exits(args, module)
  File "/home/jurre/dev/exitmap/src/exitmap.py", line 302, in select_exits
    hosts=hosts)
  File "/home/jurre/dev/exitmap/src/relayselector.py", line 109, in get_exits
    for desc in stem.descriptor.parse_file(cached_descriptors_path):
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/__init__.py", line 161, in parse_file
    for desc in handler(descriptor_file, descriptor_type, validate, document_handler, **kwargs):
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/__init__.py", line 226, in _parse_file_for_path
    for desc in parse_file(desc_file, *args, **kwargs):
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/__init__.py", line 211, in parse_file
    for desc in file_parser(descriptor_file):
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/server_descriptor.py", line 157, in _parse_file
    yield RelayDescriptor(descriptor_text, validate, annotations, **kwargs)
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/server_descriptor.py", line 665, in __init__
    super(RelayDescriptor, self).__init__(raw_contents, validate, annotations)
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/server_descriptor.py", line 302, in __init__
    self._parse(entries, validate)
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/server_descriptor.py", line 819, in _parse
    ServerDescriptor._parse(self, entries, validate)
  File "/usr/lib/python2.7/dist-packages/stem/descriptor/server_descriptor.py", line 494, in _parse
    raise ValueError('Extra-info digests should consist of forty hex digits: %s' % value)
ValueError: Extra-info digests should consist of forty hex digits: 17FCF4A1A749301A0B4710323ABE1C123DC30824 p3Hrg+Cn86Vc13zsyFYDBtETPZJC/fKphySA3R5WI0A
```

**Comment by NullHypothesis** [comment] 2016-03-01 19:46
That's a duplicate of https://github.com/NullHypothesis/exitmap/issues/28.

**Closed by NullHypothesis** 2016-03-01 19:46 UTC
